language: php
dist: trusty
sudo: required

php:
  - '5.6'
 
services:
  - mysql
 
env:
  - CI_ENV=testing
 
before_install:
  - sudo apt-get install lftp
  
before_script:
  - chmod 0777 ./bin/test.sh
  - chmod 0777 ./bin/deploy.sh
 
script: ./bin/test.sh
 
after_success:
  - ./bin/deploy.sh